# Generated by Django 4.2.10 on 2025-05-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='last_known_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('in_center', 'In Center'), ('off_premises', 'Off Premises'), ('escaped', 'Escaped'), ('unknown', 'Unknown')], default='in_center', max_length=20),
        ),
        migrations.CreateModel(
            name='ChildAIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escape_risk_score', models.FloatField(default=0.0)),
                ('last_evaluated', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to='children.child')),
            ],
        ),
    ]
