# Generated by Django 4.2.10 on 2025-05-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Center', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('safe_radius_m', models.FloatField(default=100.0)),
            ],
        ),
    ]
