# Generated by Django 4.2.10 on 2025-05-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_notify_push',
            field=models.BooleanField(default=True),
        ),
    ]
